  - name: Download Apache source
    get_url:
      url: "{{ apache_url }}"
      dest: "{{ apache_tar }}"
      mode: '0644'

  - name: Extract Apache source
    unarchive:
      src: "{{ apache_tar }}"
      dest: "/tmp"
      remote_src: yes
      creates: "{{ apache_src_dir }}"

  - name: Configure Apache build
    command: ./configure --prefix={{ apache_prefix }} --enable-so --enable-ssl --enable-rewrite
    args:
      chdir: "{{ apache_src_dir }}"

  - name: Compile Apache
    command: make
    args:
      chdir: "{{ apache_src_dir }}"

  - name: Install Apache
    command: make install
    args:
      chdir: "{{ apache_src_dir }}"

  - name: Ensure httpd.conf exists
    stat:
      path: "{{ apache_prefix }}/conf/httpd.conf"
    register: conf_stat

  - name: Backup httpd.conf if exists
    copy:
      src: "{{ apache_prefix }}/conf/httpd.conf"
      dest: "{{ apache_prefix }}/conf/httpd.conf.bak"
      remote_src: yes
    when: conf_stat.stat.exists

  - name: Customize httpd.conf (enable vhost include, server name, etc.)
    lineinfile:
      path: "{{ apache_prefix }}/conf/httpd.conf"
      regexp: '^#?ServerName'
      line: "ServerName localhost"
      state: present

  - name: Start Apache
    command: "{{ apache_prefix }}/bin/apachectl -k start"

  - name: Verify Apache is running
    shell: pgrep httpd
    register: apache_status
    changed_when: false

  # - name: Ensure Apache bin path is in user bashrc
  #   shell: |
  #       export PATH=$PATH:/usr/local/apache2/bin
  #       source ~/.bashrc
  #   become_user: bashrc

  - name: enable loadModule proxy_module
    replace: 
      path: /usr/local/apache2/conf/httpd.conf
      regexp: '#LoadModule rewrite_module modules/mod_rewrite.so'
      replace: 'LoadModule rewrite_module modules/mod_rewrite.so'

  # - name: edit httpd.conf
  #   template:
  #     src: httpd.conf.j2
  #     dest: /usr/local/apache2/conf/extra/httpd-vhosts.conf 

  - name: Enable Apache vhosts include in httpd.conf
    replace:
      path: /usr/local/apache2/conf/httpd.conf
      regexp: '^#Include conf/extra/httpd-vhosts.conf'
      replace: 'Include conf/extra/httpd-vhosts.conf'

  - name: Enable required Apache modules
    lineinfile:
      path: /usr/local/apache2/conf/httpd.conf
      regexp: "^#?LoadModule proxy_module modules/mod_proxy.so"
      line: "LoadModule proxy_module modules/mod_proxy.so"

  - name: Enable proxy_fcgi_module
    lineinfile:
      path: /usr/local/apache2/conf/httpd.conf
      regexp: "^#?LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so"
      line: "LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so"

  - name: Enable dir_module
    lineinfile:
      path: /usr/local/apache2/conf/httpd.conf
      regexp: "^#?LoadModule dir_module modules/mod_dir.so"
      line: "LoadModule dir_module modules/mod_dir.so"
    
  - name: Restart custom Apache
    command: /usr/local/apache2/bin/apachectl restart