    - name: Add Sury PHP repository (Debian)
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present

    - name: Add PHP repo to sources.list.d
      apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
        state: present

    - name: "Install PHP 8.2 and modules"
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - php8.2
        - php8.2-fpm
        - php8.2-curl
        - php8.2-xml
        - php8.2-mbstring
        - php8.2-gd
        - php8.2-imagick
        - php8.2-imap
        - php8.2-intl
        - php8.2-mysql
        - php8.2-pgsql
        - php8.2-zip

        